### ISSUE TITLE
BitBucket support

### ISSUE THREAD

**Issue by devgru** [vmarchaud/pm2-githook#2]
Is it possible to use bitbucket repo to trigger hooks?

I get "OK" response if I just trigger URL with browser or bitbucket hook but no rebuild happens

**Comment by vmarchaud** [comment]
Yeah, no problem, can you past me here the exact post data of the webhook ?

**Comment by devgru** [comment]
Here you are: http://pastebin.com/qtqZA2k0

Thanks for fast response!

**Comment by vmarchaud** [comment]
Will add it later today

**Comment by devgru** [comment]
Any updates?

**Comment by vmarchaud** [comment]
Not so much, i planned to look into it today (busy this week), do you know if there is any way to secure the endpoint so validate that the request has been made by bitbucket ?

**Comment by devgru** [comment]
I'd be happy to help you dealing with this issue.


[Bitbucket docs](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html
) says:

> If you want your server to check that the payloads it receives are from Bitbucket, whitelist this IP range: 104.192.143.0/24

Looks like this is the only way to validate request origin.

**Comment by vmarchaud** [comment]
Yeah, implemented the ip check, i'll test and publish

**Comment by vmarchaud** [comment]
Got some problem with ip-parsing, it should work now (just published under ``1.7.2`)

**Comment by devgru** [comment]
It works! Thank you very much.
