### ISSUE TITLE
Security vulnerability: Using X-Forwarded-For without option of disabling

### ISSUE THREAD

**Issue by craftbyte** [vmarchaud/pm2-githook#29]
In the handler for HTTP, `X-Forwarded-For` is implicitly trusted. If the pm2 app is exposed directly to the internet, someone can inject their own value into the header, bypassing the bitbucket IP check. Please make a config option that is disabled by default for using the header when running reverse-proxies.

**Comment by vmarchaud** [comment]
https://github.com/vmarchaud/pm2-githook/commit/73a36e7577bbc8d6bc25fa751afa8102f75a7c84
