### ISSUE TITLE
Github branch support

### ISSUE THREAD

**Issue by capaci** [vmarchaud/pm2-githook#9]
Hi, I'm using this module and I think it's amazing. 
However I'm running in troubles, because it doesn't support github branches, so every push event on github runs all build tasks, overloading my server. As an example, last week I deleted many useless branch on my repo and the hook was dispatch for each delete, because a branch deletion is considered a push event for github, and my server got down.

I took a look in [github webhook documentation](https://developer.github.com/v3/activity/events/types/#pushevent) and I saw that they send a payload field with the branch that was updated.

An example of payload sent:
![image](https://user-images.githubusercontent.com/4624073/38456365-7504815e-3a5a-11e8-9fe8-7b3f448f579f.png)

Can I submit a pull request with a new option to support github branches?

Thanks.

**Comment by vmarchaud** [comment]
Yes, i will review it and merge it ;)
